name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master

jobs:
  # make sure build/ci work properly
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: build and test
      run: |
        npm install
        npm run all

  # make sure the action works on a clean machine without building
  e2e:
    if: github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Datadog
      uses: ./
      with:
        api-key: ${{ secrets.DATADOG_API_KEY }}
        metrics: |
          - type: "count"
            name: "test.runs.count"
            value: 1.0
            tags:
              - "project:${{ github.repository }}"
              - "branch:${{ github.head_ref }}"
        events: |
          - title: "Test run succesfully"
            text: "GitHub job ${{ github.job }} ran successfully"
            alert_type: "info"
            host: ${{ github.repository_owner }}
            tags:
              - "project:${{ github.repository }}"
